import {test,expect} from '@playwright/test';
import {initialState,blankEntry} from '../../src/model.js';
import {openAccount} from './ui-helpers.js';
import ExcelJS from 'exceljs';
import fs from 'node:fs/promises';
import {readPdf} from '../helpers/read-pdf.js';
const seed=()=>({...initialState(),entries:[['sep-one','2026-09-10'],['sep-two','2026-09-20'],['oct-one','2026-10-02']].map(([id,date])=>({...blankEntry(),id,date,name:'Customer '+id,number:id,types:['SV'],addons:['Elite']}))});
async function start(page){await page.goto('/');await page.evaluate(s=>localStorage.setItem('dispensing-record:v1',JSON.stringify(s)),seed());await page.reload();await page.locator('#tab-claims').click();}
async function create(page,name,ids){await page.getByRole('button',{name:'Create claim',exact:true}).click();await page.locator('#claim-name').fill(name);for(const id of ids)await page.locator(`#claim-choices input[value="${id}"]`).check();await page.getByRole('button',{name:'Save draft claim',exact:true}).click();}
test('claims reserve receipts across months, export fixed totals and persist submission/undo history',async({page})=>{
 await start(page);await create(page,'September bonuses',['sep-one']);
 await expect(page.locator('#claim-detail')).toContainText('Draft · 1 record · €2.00');
 await page.getByRole('button',{name:'Download claim',exact:true}).click();
 let downloading=page.waitForEvent('download');await page.locator('#download-export').click();let file=await downloading;const book=new ExcelJS.Workbook();await book.xlsx.readFile(await file.path());expect(book.worksheets[0].getCell('Q5').value).toBe(2);
 await expect(page.locator('#claim-list')).toContainText('Draft');await page.locator('#claim-list button').first().click();page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Mark submitted',exact:true}).click();await page.getByRole('button',{name:'Close claim',exact:true}).click();
 await page.reload();await page.locator('#tab-records').click();await expect(page.getByRole('button',{name:'Edit Customer sep-one',exact:true})).toHaveCount(0);await expect(page.locator('#records')).toContainText('Submitted · September bonuses');
 await openAccount(page);await page.getByRole('button',{name:'Bonus key',exact:true}).click();await page.getByLabel('Elite 1st set rate',{exact:true}).fill('9');page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Save bonus key',exact:true}).click();
 await page.locator('#tab-claims').click();await page.locator('#claim-list button').first().click();await page.getByRole('button',{name:'Download claim',exact:true}).click();await page.locator('#export-format').selectOption('pdf');downloading=page.waitForEvent('download');await page.locator('#download-export').click();file=await downloading;const pages=await readPdf(await fs.readFile(await file.path()));expect(pages[0].text).toMatch(/TOTAL BONUS\s+€2.00/);
 await page.getByRole('button',{name:'Create claim',exact:true}).click();await expect(page.locator('#claim-choices input[value="sep-one"]')).toHaveCount(0);await page.locator('#claim-name').fill('October bonuses');for(const id of ['sep-two','oct-one'])await page.locator(`#claim-choices input[value="${id}"]`).check();await page.getByRole('button',{name:'Save draft claim',exact:true}).click();await expect(page.locator('#claim-detail')).toContainText('€18.00');await page.getByRole('button',{name:'Close claim',exact:true}).click();
 await page.locator('#claim-list button').filter({hasText:'September bonuses'}).click();page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Undo submission',exact:true}).click();await expect(page.locator('#claim-detail')).toContainText('Submission undone');await page.getByRole('button',{name:'Close claim',exact:true}).click();await expect(page.locator('#claim-summary')).toHaveText('1 unclaimed record');
 await page.setViewportSize({width:320,height:740});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
test('duplicate warning identifies submitted receipt and cancelling keeps only the original',async({page})=>{
 await start(page);await create(page,'Sent',['sep-one']);page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Mark submitted',exact:true}).click();await page.getByRole('button',{name:'Close claim',exact:true}).click();await page.locator('#tab-entry').click();await page.getByLabel('Date',{exact:true}).fill('2026-09-10');await page.getByLabel('Customer number',{exact:true}).fill('sep-one');await page.getByLabel('Customer name',{exact:true}).fill('Duplicate customer');await page.locator('input[name="types"][value="SV"]').check();
 page.once('dialog',async d=>{expect(d.message()).toContain('submitted in Sent');await d.dismiss();});await page.getByRole('button',{name:'Save dispense',exact:true}).click();await expect(page.locator('#count')).toHaveText('3');
});
test('claim selection filters dates without losing selections and cancelled drafts release records',async({page})=>{
 await start(page);await page.getByRole('button',{name:'Create claim',exact:true}).click();await page.locator('#claim-choices input[value="sep-one"]').check();await page.getByText('Filter by dispense date',{exact:true}).click();await page.locator('#claim-from').fill('2026-10-01');await expect(page.locator('#claim-choices input')).toHaveCount(1);await page.getByRole('button',{name:'Select visible',exact:true}).click();await expect(page.locator('#claim-selection-total')).toContainText('2 selected');await page.getByRole('button',{name:'Save draft claim',exact:true}).click();await expect(page.locator('#claim-detail')).toContainText('€4.00');page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Cancel draft',exact:true}).click();await page.getByRole('button',{name:'Close claim',exact:true}).click();await expect(page.locator('#claim-summary')).toHaveText('3 unclaimed records');await page.reload();await page.locator('#tab-claims').click();await expect(page.locator('#claim-list')).toContainText('Draft cancelled');
});
