import { test, expect } from '@playwright/test';
import { blankEntry, initialState } from '../../src/model.js';
import { showRecords } from './ui-helpers.js';

test('one third-pair offer opens independent add-ons, survives editing, and clears for the next customer',async({page})=>{
  await page.goto('/');
  if (page.viewportSize().width<500) await page.setViewportSize({width:320,height:740});
  await page.getByLabel('Customer number',{exact:true}).fill('001');
  await page.getByLabel('Customer name',{exact:true}).fill('Three pairs');
  const select=value=>page.locator(`input:not([name="thirdAddons"])[value="${value}"]`).check();
  for(const value of ['241','160','190','UCSC','second','UCSC']) await select(value);
  await page.locator('.offers summary').click();
  await expect(page.locator('#third-pair-addons')).toBeHidden();
  await page.getByLabel('Golden Ticket / Third pair half price',{exact:true}).check();
  await expect(page.locator('#third-pair-addons')).toBeVisible();
  await expect(page.locator('input[name="thirdAddons"]:checked')).toHaveCount(0);
  for(const value of ['Tailormade','1.74','Super Boost']) await page.locator(`input[name="thirdAddons"][value="${value}"]`).check();
  await expect(page.locator('#bonus-preview .bonus-line strong')).toHaveText('€9.50');
  await expect(page.locator('#bonus-preview .breakdown')).toContainText('3rd pair · Super Boost €1.00');
  await select('first');
  await expect(page.locator('input[name="addons"][value="UCSC"]')).toBeChecked();
  await expect(page.locator('input[name="thirdAddons"]:checked')).toHaveCount(3);
  await page.locator('#third-pair-enabled').uncheck();
  await expect(page.locator('#third-pair-addons')).toBeHidden();
  await expect(page.locator('#bonus-preview .bonus-line strong')).toHaveText('€6.50');
  await page.locator('#third-pair-enabled').check();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.getByRole('button',{name:'Save dispense',exact:true}).click();
  await expect(page.locator('#third-pair-enabled')).not.toBeChecked();
  await expect(page.locator('input[name="thirdAddons"]:checked')).toHaveCount(0);
  await page.reload();await expect(page.locator('#total')).toHaveText('€9.50');
  await showRecords(page);await expect(page.locator('#records')).toContainText('3rd pair: 1.74 + Tailormade + Super Boost');
  await page.getByRole('button',{name:'Edit Three pairs',exact:true}).click();
  await expect(page.locator('#third-pair-enabled')).toBeChecked();
  await expect(page.locator('input[name="thirdAddons"]:checked')).toHaveCount(3);
  await page.locator('input[name="thirdAddons"][value="1.74"]').uncheck();
  await page.getByRole('button',{name:'Save changes',exact:true}).click();
  await expect(page.locator('#total')).toHaveText('€8.50');
  await page.locator('.offers summary').click();await page.locator('#third-pair-enabled').check();
  await page.locator('input[name="thirdAddons"][value="Tint"]').check();
  await page.getByRole('button',{name:'Clear form',exact:true}).click();
  await expect(page.locator('#third-pair-enabled')).not.toBeChecked();
  await expect(page.locator('input[name="thirdAddons"]:checked')).toHaveCount(0);
});

test('older third-pair offers need explicit add-on review without copying first-set choices',async({page})=>{
  const state=initialState();state.entries=[{...blankEntry(),id:'old',number:'001',name:'Older offer',types:['241'],addons:['Polaroid'],offers:['Golden Ticket','3rd pair half-price combined with 2-4-1']}];
  await page.goto('/');await page.evaluate(state=>localStorage.setItem('dispensing-record:v1',JSON.stringify(state)),state);await page.reload();
  await expect(page.locator('#total-caption')).toContainText('1 pending');
  await showRecords(page);await page.getByRole('button',{name:'Edit Older offer',exact:true}).click();
  await expect(page.locator('#third-pair-enabled')).toBeChecked();
  await expect(page.locator('#third-pair-review')).toBeVisible();
  await expect(page.locator('input[name="thirdAddons"]:checked')).toHaveCount(0);
  await expect(page.locator('input[name="addons"][value="Polaroid"]')).toBeChecked();
  await page.locator('input[name="thirdAddons"][value="Elite"]').check();
  await page.getByRole('button',{name:'Save changes',exact:true}).click();
  await expect(page.locator('#total')).toHaveText('€4.00');
  await page.reload();await expect(page.locator('#total')).toHaveText('€4.00');
});
